diff a/fs/Makefile b/fs/Makefile	(rejected hunks)
@@ -128,4 +129,4 @@ obj-$(CONFIG_PSTORE)		+= pstore/
 # Patched by YAFFS
 obj-$(CONFIG_YAFFS_FS)		+= yaffs2/
 
-obj-$(CONFIG_DYNAMIC_FSYNC)	+= dyn_sync_cntrl.o
\ No newline at end of file
+obj-$(CONFIG_DYNAMIC_FSYNC)	+= dyn_sync_cntrl.o
